### ISSUE TITLE
Миграция на Leanpub

### ISSUE THREAD

**Issue by lex111** [ellysh/video-game-bots-ru#4]
Чек-лист:

- [x] Использовать новый [Markua](https://leanpub.com/markua/read) ?
- [x] Перенести изображения в одну папку (например, images/chapter-name/img-name.ext), изменить соответствующим образом пути к изображениям

- [ ]  Конвертировать листинги

До:

```
_**Листинг 2-1.** Скрипт `Send.au3`_
```AutoIt
$hWnd = WinGetHandle("[CLASS:Notepad]")
WinActivate($hWnd)
Send("a")
` ``
```

После:

```
{caption: "Листинг 2-1. Скрипт `Send.au3"}
```AutoIt
$hWnd = WinGetHandle("[CLASS:Notepad]")
WinActivate($hWnd)
Send("a")
` ``
```

- [x]  Конвертировать вставки (использовать Aside или Blurb)

До:

```
---
Во всех примерах мы будем использовать 32-разрядную версию тестового приложения.
---
```

После:

```
A> Во всех примерах мы будем использовать 32-разрядную версию тестового приложения.
```

cc @ellysh

**Comment by ellysh** [comment]
Листинги пока остались в Markdown формате.
